name: ci

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  node_version: 10.x  # from .travis, what about 12.x (Active LTS)?

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}
    - run: npm install
    - name: Lint project
      run: npm run lint:all